name: Instagram Scraper

on:
  workflow_dispatch:
    inputs:
      profile_url:
        description: 'Instagram Profile URL'
        required: true
      start_date:
        description: 'Start Date (YYYY-MM-DD)'
        required: true
      end_date:
        description: 'End Date (YYYY-MM-DD)'
        required: true
      username:
        description: 'Instagram Username'
        required: true
      password:
        description: 'Instagram Password'
        required: true

jobs:
  scrape:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper
      run: python scraper.py "${{ github.event.inputs.profile_url }}" "${{ github.event.inputs.start_date }}" "${{ github.event.inputs.end_date }}" "${{ github.event.inputs.username }}" "${{ github.event.inputs.password }}"

    - name: Upload scraped CSV as artifact
      uses: actions/upload-artifact@v4
      with:
        name: scraped_data
        path: "*.csv"
