name: Run Instagram Scraper

on:
  workflow_dispatch:
    inputs:
      profile_url:
        description: "Instagram profile URL"
        required: true
      start_date:
        required: true
      end_date:
        required: true
      username:
        required: true
      password:
        required: true

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install undetected-chromedriver selenium pandas

      # 🧩 Fix Chrome / ChromeDriver version mismatch
      - name: Fix Chrome version mismatch
        run: |
          pip install undetected-chromedriver==3.5.5
          google-chrome --version || chromium-browser --version
          python -m undetected_chromedriver --version

      # 🛠 Optional: Pin Chrome version (if mismatch persists)
      - name: Install specific Chrome version
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable=140.0.7339.0-1 || true
          google-chrome --version || chromium-browser --version

      - name: Run Scraper
        run: |
          python scraper.py \
            "${{ github.event.inputs.profile_url }}" \
            "${{ github.event.inputs.start_date }}" \
            "${{ github.event.inputs.end_date }}" \
            "${{ github.event.inputs.username }}" \
            "${{ github.event.inputs.password }}"

      - name: Upload scraped CSV
        uses: actions/upload-artifact@v4
        with:
          name: scraped_data
          path: scraped_data.csv
