name: Run Instagram Scraper

on:
  workflow_dispatch:
    inputs:
      profile_url:
        description: "Instagram profile URL"
        required: true
      start_date:
        required: true
      end_date:
        required: true
      username:
        required: true
      password:
        required: true

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install selenium pandas

      # 🟢 Install Microsoft Edge and EdgeDriver
      - name: Setup Edge
        run: |
          sudo apt update
          sudo apt install -y microsoft-edge-stable unzip
          EDGE_VERSION=$(microsoft-edge --version | awk '{print $3}' | cut -d '.' -f1)
          wget https://msedgedriver.azureedge.net/${EDGE_VERSION}.0/edgedriver_linux64.zip
          unzip edgedriver_linux64.zip -d $HOME/edgedriver
          export PATH=$PATH:$HOME/edgedriver

      - name: Run Scraper
        run: python scraper.py

      - name: Upload scraped CSV
        uses: actions/upload-artifact@v4
        with:
          name: scraped_data
          path: "*.csv"
