name: Instagram Scraper

on:
  workflow_dispatch:
    inputs:
      profile_url:
        description: 'Instagram Profile URL'
        required: true
      start_date:
        description: 'Start Date (YYYY-MM-DD)'
        required: true
      end_date:
        description: 'End Date (YYYY-MM-DD)'
        required: true
      username:
        description: 'Instagram Username'
        required: true
      password:
        description: 'Instagram Password'
        required: true

jobs:
  scrape:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas selenium

    - name: Download Edge WebDriver
      run: |
        # Install latest Edge WebDriver automatically
        Invoke-WebRequest -Uri "https://msedgedriver.azureedge.net/LATEST_RELEASE" -OutFile latest.txt
        $version = Get-Content latest.txt
        Invoke-WebRequest -Uri "https://msedgedriver.azureedge.net/$version/edgedriver_win64.zip" -OutFile "edgedriver.zip"
        Expand-Archive edgedriver.zip -DestinationPath $Env:USERPROFILE\edgedriver
        echo "PATH=$Env:USERPROFILE\edgedriver;$Env:PATH" >> $Env:GITHUB_ENV

    - name: Run scraper
      run: |
        python scraper.py "$env:PROFILE_URL" "$env:START_DATE" "$env:END_DATE" "$env:USERNAME" "$env:PASSWORD"
      env:
        PROFILE_URL: ${{ github.event.inputs.profile_url }}
        START_DATE: ${{ github.event.inputs.start_date }}
        END_DATE: ${{ github.event.inputs.end_date }}
        USERNAME: ${{ github.event.inputs.username }}
        PASSWORD: ${{ github.event.inputs.password }}
