name: Run Instagram Scraper

on:
  workflow_dispatch:
    inputs:
      profile_url:
        description: "Instagram profile URL"
        required: true
      start_date:
        required: true
      end_date:
        required: true
      username:
        required: true
      password:
        required: true

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install undetected-chromedriver==3.5.5 selenium pandas

      # -------------------------------
      # Install Chrome 141 to match driver
      # -------------------------------
      - name: Install Chrome 141
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg2
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_141.0.0.0-1_amd64.deb
          sudo dpkg -i google-chrome-stable_141.0.0.0-1_amd64.deb || true
          sudo apt-get install -f -y
          google-chrome --version

      - name: Run Scraper
        run: |
          python scraper.py \
            "${{ github.event.inputs.profile_url }}" \
            "${{ github.event.inputs.start_date }}" \
            "${{ github.event.inputs.end_date }}" \
            "${{ github.event.inputs.username }}" \
            "${{ github.event.inputs.password }}"

      - name: Upload scraped CSV
        uses: actions/upload-artifact@v4
        with:
          name: scraped_data
          path: scraped_data.csv
